sudo: required
services:
  - docker
before_install:
  - docker build -t julianosousa/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true julianosousa/docker-react npm run test
language: generic 